version: "3.6"
volumes:
  bundle:
  postgres:
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: web
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PGHOST=postgres
      - PGUSER=admin
      - PGPASSWORD=admin
      - RAILS_LOG_STDOUT=1
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  worker:
    image: web
    command: bundle exec sidekiq -q high -q default -q low
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PGHOST=postgres
      - PGUSER=admin
      - PGPASSWORD=admin
      - RAILS_LOG_STDOUT=1
      - RAILS_MAX_THREADS=50
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12.4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/app
  redis:
    image: redis:4
